language: node_js
node_js:
- 12.9.1
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 49.235.211.168
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh travis@49.235.211.168 -o StrictHostKeyChecking=no 'cd ~/juejin-ranking && git
  pull && npm install && npm run build && pm2 start npm -- run start --name juejin'
