# .travis.yml
language: node_js #前端工程所以是JavaScript，编译环境是node_js
node_js:
  - '8' #指定node版本
branchs:
  only:
    - master #指定只有检测到master分支有变动时才执行任务
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts:
    - m3lt.cn #受信主机，你的Linux服务器ip
after_success:
  - chmod 600 ~/.ssh/id_rsa #还是Linux文件权限问题
  - ssh travis@m3lt.cn -o StrictHostKeyChecking=no 'cd ~/juejin-ranking && git pull && npm install && npm run build' #使用ssh连接服务
